import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { Product } from '../interfaces/product';
@Injectable({
  providedIn: 'root',
})
export class ProductService {

  static products: Product[] = [
    {
      name: 'Halawa Croissant',
      image: 'images/products/bakery-1.webp',
      price: 35.0,
      discount: 0,
      amount: 35,
      category: 'bakery',
      id: 'B1',
    },
    {
      name: 'Sesame & Cumin Baton Sale',
      image: 'images/products/bakery-5.png',
      price: 190.0,
      discount: 0,
      amount: 2,
      category: 'bakery',
      id: 'B5',
    },
    {
      name: 'Cumin Baton Sale',
      image: 'images/products/bakery-6.png',
      price: 190.0,
      discount: 25,
      amount: 4,
      category: 'bakery',
      id: 'B6',
    },
    {
      name: 'Orange Cake Large',
      image: 'images/products/bakery-2.png',
      price: 155.0,
      discount: 0,
      amount: 35,
      category: 'bakery',
      id: 'B2',
    },
    {
      name: 'Mini Sandwich - 10 Pieces',
      image: 'images/products/bakery-3.png',
      price: 90.0,
      discount: 0,
      amount: 35,
      category: 'bakery',
      id: 'B3',
    },
    {
      name: 'Sesame Baton Sale',
      image: 'images/products/bakery-4.png',
      price: 190.0,
      discount: 10,
      amount: 35,
      category: 'bakery',
      id: 'B4',
    },
    {
      name: 'White Cheese Paté',
      image: 'images/products/bakery-7.png',
      price: 33.0,
      discount: 15,
      amount: 0,
      category: 'bakery',
      id: 'B7',
    },
    {
      name: 'Roumi Cheese Paté',
      image: 'images/products/bakery-8.png',
      price: 35.0,
      discount: 0,
      amount: 33,
      category: 'bakery',
      id: 'B8',
    },
    {
      name: 'Boghasha',
      image: 'images/products/bakery-9.png',
      price: 36.0,
      discount: 0,
      amount: 11,
      category: 'bakery',
      id: 'B9',
    },
    {
      name: 'Italian Pizza',
      image: 'images/products/bakery-10.png',
      price: 36.0,
      discount: 10,
      amount: 33,
      category: 'bakery',
      id: 'B10',
    },
    {
      name: 'Mini Sandwich - 10 Pieces',
      image: 'images/products/bakery-3.png',
      price: 90.0,
      discount: 0,
      amount: 35,
      category: 'bakery',
      id: 'B11',
    },
    {
      name: 'Sesame Baton Sale',
      image: 'images/products/bakery-4.png',
      price: 190.0,
      discount: 10,
      amount: 3,
      category: 'bakery',
      id: 'B12',
    },
    {
      name: 'Chocolate chateau',
      image: 'images/products/cake-1.png',
      price: 480.0,
      discount: 0,
      amount: 8,
      category: 'cake',
      id: 'C1',
    },
    {
      name: 'Fruits Cake 30',
      image: 'images/products/cake-2.webp',
      price: 605.0,
      discount: 10,
      amount: 12,
      category: 'cake',
      id: 'C2',
    },
    {
      name: 'Black Forest Cake26',
      image: 'images/products/cake-3.png',
      price: 430.0,
      discount: 0,
      amount: 12,
      category: 'cake',
      id: 'C3',
    },
    {
      name: 'Choco Sponge Cake 30x30',
      image: 'images/products/cake-4.png',
      price: 570.0,
      discount: 0,
      amount: 12,
      category: 'cake',
      id: 'C4',
    },
    {
      name: 'Choco Sponge Cake26',
      image: 'images/products/cake-5.png',
      price: 385.0,
      discount: 0,
      amount: 3,
      category: 'cake',
      id: 'C5',
    },
    {
      name: 'Chocolate Mix Cake',
      image: 'images/products/cake-6.png',
      price: 410.0,
      discount: 10,
      amount: 2,
      category: 'cake',
      id: 'C6',
    },
    {
      name: 'Fudge Cake 26',
      image: 'images/products/cake-7.png',
      price: 430.0,
      discount: 10,
      amount: 12,
      category: 'cake',
      id: 'C7',
    },
    {
      name: 'Flamenco Cake26',
      image: 'images/products/cake-8.png',
      price: 430.0,
      discount: 0,
      amount: 0,
      category: 'cake',
      id: 'C8',
    },
    {
      name: 'Fruits Cake 26',
      image: 'images/products/cake-9.png',
      price: 465.0,
      discount: 15,
      amount: 12,
      category: 'cake',
      id: 'C9',
    },
    {
      name: 'Four Seasons Cake 26',
      image: 'images/products/cake-10.png',
      price: 430.0,
      discount: 0,
      amount: 1,
      category: 'cake',
      id: 'C10',
    },
    {
      name: 'Four Seasons Cake 30x30',
      image: 'images/products/cake-11.png',
      price: 685.0,
      discount: 0,
      amount: 15,
      category: 'cake',
      id: 'C11',
    },
    {
      name: 'Duetto Fruits & Flamenco 30x30',
      image: 'images/products/cake-12.webp',
      price: 695.0,
      discount: 10,
      amount: 15,
      category: 'cake',
      id: 'C12',
    },
    {
      name: 'Chocolate Foulya',
      image: 'images/products/chocolate-1.png',
      price: 43.0,
      discount: 0,
      amount: 15,
      category: 'chocolate',
      id: 'Ch1',
    },
    {
      name: 'Chocolate-coated Shakalama',
      image: 'images/products/chocolate-2.png',
      price: 50.0,
      discount: 0,
      amount: 9,
      category: 'chocolate',
      id: 'Ch2',
    },
    {
      name: 'Chocolate-coated Hazelnut',
      image: 'images/products/chocolate-3.png',
      price: 65.0,
      discount: 10,
      amount: 11,
      category: 'chocolate',
      id: 'Ch3',
    },
    {
      name: 'Chocolate Nougat with Peanuts',
      image: 'images/products/chocolate-4.png',
      price: 35.0,
      discount: 0,
      amount: 13,
      category: 'chocolate',
      id: 'Ch4',
    },
    {
      name: 'Chocolate Delights Box Small',
      image: 'images/products/chocolate-7.png',
      price: 360.0,
      discount: 10,
      amount: 2,
      category: 'chocolate',
      id: 'Ch5',
    },
    {
      name: 'Chocolate Delights Box Large',
      image: 'images/products/chocolate-7.png',
      price: 580.0,
      discount: 0,
      amount: 11,
      category: 'chocolate',
      id: 'Ch6',
    },
    {
      name: 'Chocolate Pouch',
      image: 'images/products/chocolate-7.png',
      price: 165.0,
      discount: 0,
      amount: 15,
      category: 'chocolate',
      id: 'Ch7',
    },
  ];

  constructor() {}

  static getProducts(): Product[] {
  return this.products;
  }
}
