# docker compose up --build -d
# docker exec -it jenkins bash
# trivy --version

version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/ahmed/Desktop/jenkins/jenkins-data/jenkins_home:/var/jenkins_home


  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - 8081:8081  # Nexus default web interface port
    # volumes:
    #   - /home/ahmed/Desktop/complete_CICD_project/nexus-data:/nexus-data  # Persistent storage for Nexus
    # environment:
    #   - NEXUS_CONTEXT=/
      
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000  # SonarQube default web interface port
    # environment:
    #   - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    #   - SONAR_JDBC_USERNAME=sonar
    #   - SONAR_JDBC_PASSWORD=sonar
    # depends_on:
    #   - db  # SonarQube depends on the PostgreSQL database
    # sysctls:
    #   net.core.somaxconn: 1024  # Optional: Increase the maximum socket connections
    #   vm.max_map_count: 262144   # This sets the max_map_count for the container

  # db:
  #   image: postgres:13
  #   container_name: sonarqube_db
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #     - POSTGRES_DB=sonarqube
  #   volumes:
  #     - /home/ahmed/Desktop/complete_CICD_project/sonarqube-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL
