---
- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

#- name: Download Kubernetes apt repository GPG key
#  get_url:
#    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
#    dest: /etc/apt/keyrings/kubernetes-apt-key.gpg
#  become: yes

- name: Copy Kubernetes GPG key to target machine
  copy:
    src: /tmp/kubernetes-apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-apt-key.gpg

- name: Add Kubernetes GPG key to APT
  apt_key:
    file: /etc/apt/keyrings/kubernetes-apt-key.gpg
    state: present


- name: Convert Kubernetes GPG key to gpg format
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-key.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: yes

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
    filename: "kubernetes"
  become: yes

- name: Update apt package index
  apt:
    update_cache: yes
  become: yes

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  become: yes

- name: Hold kubelet, kubeadm, and kubectl versions
  command: apt-mark hold kubelet kubeadm kubectl
  become: yes

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: true
    state: started
  become: yes

