---
- name: Deploy Docker Images
  become: yes
  vars:
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -i ~/.ssh/mykey ubuntu@{{ hostvars['frontend-server'].ansible_host }}"
    ansible_user: ubuntu
  hosts: frontend-server
  tasks:
    - name: Pull frontend image
      docker_image:
        name: janaessam/devops_frontend
        source: pull
        tag: latest

    - name: Run frontend container
      docker_container:
        name: react-frontend
        image: janaessam/devops_frontend:latest
        ports:
          - "3000:80"
        restart_policy: always

- name: Deploy Docker Images
  become: yes
  vars:
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -i ~/.ssh/mykey ubuntu@{{ hostvars['frontend-server'].ansible_host }}"
    ansible_user: ubuntu
  hosts: backend-server
  tasks:
    - name: Pull backend image
      docker_image:
        name: janaessam/devops_backend
        source: pull
        tag: latest

    - name: Run backend container
      docker_container:
        name: node-backend
        image: janaessam/devops_backend:latest
        ports:
          - "5000:5000"
        env:
          MONGO_URI: mongodb://mongo:27017/mydatabase
        restart_policy: always

- name: Deploy Docker Images
  become: yes
  vars:
    ansible_ssh_common_args: >-
      -o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p -i ~/.ssh/mykey ubuntu@{{ hostvars['frontend-server'].ansible_host }}"
    ansible_user: ubuntu
  hosts: db-server
  tasks:
    - name: Pull MongoDB image
      docker_image:
        name: mongo
        source: pull
        tag: latest

    - name: Run MongoDB container
      docker_container:
        name: mongodb
        image: mongo:latest
        ports:
          - "27017:27017"
        restart_policy: always
