plugin: amazon.aws.aws_ec2
cache: false
use_ssm_inventory: true
# Limit query to regions
regions:
  - eu-north-1
# A named AWS profile to use for authentication.
profile: 481665091509
# Create Ansible hosts groups using the following elements: 
keyed_groups:
  - prefix: tag
    key: tags
  - prefix: instance_type
    key: instance_type
hostnames:
- tag:private_name

compose:
  ansible_host:  public_ip_address | default(private_ip_address) 