- hosts: aws_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Create a directory for Prometheus
      file:
        path: /etc/prometheus
        state: directory

    - name: Download Prometheus binary
      get_url:
        url: https://github.com/prometheus/prometheus/releases/latest/download/prometheus-2.34.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus binary
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /etc/prometheus/
        remote_src: yes

    - name: Create Prometheus configuration directory
      file:
        path: /etc/prometheus/config
        state: directory

    - name: Create a Prometheus config file
      copy:
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
        dest: /etc/prometheus/config/prometheus.yml

    - name: Create a Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=root
          Group=root
          Type=simple
          ExecStart=/etc/prometheus/prometheus --config.file /etc/prometheus/config/prometheus.yml
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started
