all:
  children:
    k8s_cluster:
      children:
        k8s_master:
          hosts:
            master:
              ansible_host: 18.185.71.252
        k8s_workers:
          hosts:
            worker1:
              ansible_host: 3.120.193.154
            worker2:
              ansible_host: 52.59.236.174
    sonarqube:
      hosts:
        sonarqube:
          ansible_host: 3.76.226.211
    nexus:
      hosts:
        nexus:
          ansible_host: 18.194.38.169
    jenkins:
      hosts:
        jenkins:
          ansible_host: 3.64.11.34
    monitoring:
      hosts:
        monitoring:
          ansible_host: 18.194.188.135
