apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: depi
  template:
    metadata:
      labels:
        app: depi
    spec:
      containers:
      - name: depi
        image: medhat22/depi-app
        ports:
        - containerPort: 3000
