apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: depi-cluster
  region: eu-north-1

managedNodeGroups:
  - name: my-nodes
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 4

    ssh: 
      allow: true
      publicKeyName: SSH
    
    labels:
      role: worker

    iam: 
      withAddonPolicies:
        autoScaler: true

