apiVersion: v1
kind: Service
metadata:
  name: lb
  annotations:
    sevice.beta.kubernetes.io/aws-load-balance-internal: "0.0.0.0/0"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: depi
  ports:
  - port: 80
    targetPort: 3000
  
