# ansible-playbook -i inventory.yml playbooks/nexus_setup.yml
---
- hosts: nexus
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  user: root
  gather_facts: yes
  tasks:

    - include_tasks: ../tasks/init.yml

    - set_fact: ansible_user=dev # switch to dev user.

    - include_tasks: ../tasks/setup_docker.yml

    - name: Run Nexus container
      docker_container:
        name: nexus
        image: sonatype/nexus3:latest
        state: started
        recreate: yes
        ports:
          - "8081:8081"
        detach: yes