---
- name: Setup Docker, Kubernetes, and Minikube on EC2 instance
  hosts: all
  become: true  # Use 'become' to run tasks as sudo
  tasks:
    - name: Update package index
      command: dnf makecache

    - name: Install necessary dependencies
      dnf:
        name: conntrack
        state: present

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Download kubectl binary
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

    - name: Make kubectl binary executable
      command: chmod +x kubectl

    - name: Move kubectl to /usr/local/bin
      command: mv kubectl /usr/local/bin/

    - name: Add Kubernetes repository
      shell: |
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOF

    - name: Install Minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 &&
        chmod +x minikube &&
        sudo mv minikube /usr/local/bin/
