plugin: aws_ec2

aws_profile: default

regions:
  - us-east-1

filters:
  tag:Team: team-1
  instance-state-name: running

keyed_groups:
  - prefix: Tag
    key: tags

groups:
  frontend: "'public' in tags.Privacy"
  backend: "'private' in tags.Privacy"
  jenkins_masters: "'master' in tags.Jenkins"
  jenkins_workers: "'worker' in tags.Jenkins"

hostnames:
  - tag:Name
  
compose:
  ansible_host: public_ip_address if tags.Name == "bastion" else private_ip_address
  ansible_ssh_common_args: >
    '-o ProxyCommand="ssh -o StrictHostKeyChecking=no -W %h:%p ubuntu@{{ hostvars["bastion"]["public_ip_address"] }}"'
    if tags.Name != "bastion" else ''
