---

- name: Deploy Jenkins on Docker
  hosts: jenkins_masters
  become: true
  gather_facts: false
  vars:
    jenkins_image: "jenkins/jenkins:lts"
    jenkins_container_name: "jenkins-server"
    jenkins_port: 8080
    jenkins_home: "/var/jenkins_home"
  roles:
    - jenkins


- name: Install Java on Jenkins Slave Nodes
  hosts: jenkins_workers
  become: true
  pre_tasks:

  - name: Update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  roles:
    - java
