apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-k8s
  namespace: flask-app
  labels:
    app: my-app-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-k8s
  template:
    metadata:
      labels:
        app: my-app-k8s
    spec:
      containers:
      - name: my-flask-app
        image: hussamgamal/flask-app:v1
        ports:
        - containerPort: 5000



