apiVersion: v1
kind: Service
metadata:
  name: my-app-k8s-service
  namespace: flask-app
spec:
  type: NodePort
  ports:
  - port: 5000          
    targetPort: 5000        
    nodePort: 30007 
  selector:
    app: my-app-k8s